# Generated by Django 4.0.2 on 2022-03-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='message',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
    ]
